name: Build and Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Configure Docker to use Google Cloud
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:${{ github.sha }}"
        docker build -t $IMAGE_NAME -f backend/Dockerfile backend/
        docker push $IMAGE_NAME

    - name: Deploy to Google Cloud VM
      run: |
        gcloud compute ssh ${{ secrets.GCP_VM_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "
          docker pull gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:${{ github.sha }} && \
          docker stop backend-container || true && \
          docker rm backend-container || true && \
          docker run -d --name backend-container -p 8000:8000 gcr.io/${{ secrets.GCP_PROJECT_ID }}/backend:${{ github.sha }}
        "

    - name: Output Base URL
      run: echo "Your backend is deployed at http://$(gcloud compute instances describe ${{ secrets.GCP_VM_NAME }} --zone ${{ secrets.GCP_ZONE }} --format='get(networkInterfaces[0].accessConfigs[0].natIP)'):8000"
